### ISSUE TITLE
通过Python json.dumps输出的Json文件解析失败

### ISSUE THREAD

**Issue by Hazukiaoi** [RickJiangShu/ConfigManager#3]
Unity版本5.6.1P1，测试项目自带的json解析正常
通过Python json.dumps输出的Json文件解析失败

python源码如下：

```python
import json

class Friend:
    def __init__(self, name, phone):
        self.name = name
        self.phone = phone

    def getDic(self):
        dic = {}
        dic['Name'] = self.name
        dic['phone'] = self.phone
        return dic
    pass


dict = {}
dict['name'] = 'Acc'
dict['age'] = 20
dict['sex'] = 'M'
dict['work'] = True

dict['Attem'] = [22,'AC',20012,False]

friendList = {}
friendList['VIP'] = {}
friendList['NON'] = {}


F001 = Friend('AC',1023)
F002 = Friend('BC',1025)
F003 = Friend('BC',1025)

friendList['VIP']['F001'] = F001.getDic()
friendList['VIP']['F002'] = F002.getDic()
friendList['NON']['F001'] = F003.getDic()

dict['FriendList'] = friendList

jsonlist = json.dumps(dict)

print(jsonlist)

```

最后获得的json如下：
```json
{"name": "Acc", "age": 20, "sex": "M", "work": true, "Attem": [22, "AC", 20012, false], "FriendList": {"VIP": {"F001": {"Name": "AC", "phone": 1023}, "F002": {"Name": "BC", "phone": 1025}}, "NON": {"F001": {"Name": "BC", "phone": 1025}}}}
```

最后文件命名为 Json1.json，并解析失败

> Json1.json解析失败！请检查格式是否正确，如果格式正确请联系作者：https://github.com/RickJiangShu/ConfigManager/issues
> System.ArgumentException: An element with the same key already exists in the dictionary.
>   at System.Collections.Generic.Dictionary`2[System.String,System.Object].Add (System.String key, System.Object value) [0x0007e] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404 
>   at ConfigManagerEditor.JsonParser.ParseObject (System.String& content) [0x00032] in F:\ConfigManager-Example-master\Assets\Editor\Parser\JSONParser.cs:85 
>   at ConfigManagerEditor.JsonParser.ParseRoot (System.String json) [0x0002d] in F:\ConfigManager-Example-master\Assets\Editor\Parser\JSONParser.cs:65 
>   at ConfigManagerEditor.JsonParser.Parse (System.String content, System.String fileName) [0x0003b] in F:\ConfigManager-Example-master\Assets\Editor\Parser\JSONParser.cs:50 
>   at ConfigManagerEditor.ConfigWindow.GetSources (System.Collections.Generic.List`1& sheets, System.Collections.Generic.List`1& structs) [0x00180] in F:\ConfigManager-Example-master\Assets\Editor\ConfigWindow.cs:288 
> UnityEngine.Debug:LogError(Object)
> ConfigManagerEditor.ConfigWindow:GetSources(List`1&, List`1&) (at Assets/Editor/ConfigWindow.cs:293)
> ConfigManagerEditor.ConfigWindow:Output() (at Assets/Editor/ConfigWindow.cs:148)
> ConfigManagerEditor.ConfigWindow:OnGUI() (at Assets/Editor/ConfigWindow.cs:94)
> UnityEditor.DockArea:OnGUI()
>

**Comment by RickJiangShu** [comment]
收到反馈，正在查明修复~

**Comment by RickJiangShu** [comment]
这个问题已经在最新的版本修复了，感谢反馈！

**Comment by Hazukiaoi** [comment]
已经测试成功
@RickJiangShu
