### ISSUE TITLE
解析json格式出现bug

### ISSUE THREAD

**Issue by zxl408** [RickJiangShu/ConfigManager#4]
{
  "Itmes": [
    {
      "Item": {
        "level": 1,
        "points": [
          {
            "point": "0,0",
            "level": 2
          }
        ]
      }
    },
    {
      "Item": {
        "level": 2,
        "points": [
          {
            "point": "0,0",
            "level": 2
          }
        ]
      }
    }
  ]
}
解析上面的json格式序列化出来的配置文件出现错乱

**Comment by RickJiangShu** [comment]
谢谢反馈，已经修复~
![image](https://user-images.githubusercontent.com/29089955/29770187-56a32eba-8c20-11e7-88f1-756ee9c854dc.png)
